import './globals.css';

import Header from './Header';
import ProvidersWrapper from './ProvidersWrapper';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children, // children,
  // header,
} // footer,
  : {
    children: React.ReactNode;
    // header: React.ReactNode;
    // footer: React.ReactNode;
  }) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body>
        <ProvidersWrapper>
          <Header />
          {children}
          {/* {header} */}
          {/* {children}
        {footer} */}
        </ProvidersWrapper>
      </body>
    </html>
  );
}
