export const metadata = {
  title: 'Products page',
  description: 'Generated by create next app',
};

export default function ProductsLayout({ children }: { children: React.ReactNode }) {
  return <div>{children}</div>;
}
